name: deploy-npm

# on events
on:
  # Only trigger this manually
  workflow_dispatch:

# env
env:
  REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

jobs:
  build-and-deploy:
    # Special exception for this branch
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file

      - name: Install dependencies
        run: npm install

      - name: Build dist
        run: npm run dist

      - name: Publish
        run: npm publish
